# Generated by Django 4.2.20 on 2025-04-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_social_network', '0002_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
