# Generated by Django 4.2.20 on 2025-05-03 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo_social_network', '0004_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like',
        ),
    ]
